// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpquqpjhogwxemfgbkyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwcXVxcGpob2d3eGVtZmdia3l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxMzg3MjgsImV4cCI6MjA1MzcxNDcyOH0.IX1Lu3ub-7qRH9d_DA0MoNqzt9ygOs4ZVZtS9lVIGn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);